/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.invistafacil.telas;


import br.com.invistafacil.business.UsuarioBusiness;
import br.com.invistafacil.dominio.Usuario;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;


/**
 *
 * @author George Alan
 */
public class CadastroTela extends javax.swing.JPanel {
    Usuario usr = new Usuario();
    UsuarioBusiness cadastro = new UsuarioBusiness();
    
    /**
     * Creates new form pnlHome
     */
    public CadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroTela = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFacaLoginAqui = new javax.swing.JLabel();
        jTextFieldTCUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTCEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldTCConfirmarSenha = new javax.swing.JPasswordField();
        rSButtonTCCriarConta = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jLabel7 = new javax.swing.JLabel();
        jLabelTCTermos = new javax.swing.JLabel();
        jPasswordFieldTCSenha = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1165, 762));

        jPanelCadastroTela.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastroTela.setPreferredSize(new java.awt.Dimension(1165, 762));
        jPanelCadastroTela.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1165, 762));

        kGradientPanel1.setkEndColor(new java.awt.Color(4, 69, 129));
        kGradientPanel1.setkGradientFocus(-1);
        kGradientPanel1.setkStartColor(new java.awt.Color(2, 42, 79));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Criar uma conta Invista Fácil");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Já possui uma conta?");

        jLabelFacaLoginAqui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFacaLoginAqui.setForeground(new java.awt.Color(255, 153, 0));
        jLabelFacaLoginAqui.setText("Faça login aqui");
        jLabelFacaLoginAqui.setToolTipText("Vá para a tela de Login");
        jLabelFacaLoginAqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFacaLoginAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFacaLoginAquiMouseClicked(evt);
            }
        });

        jTextFieldTCUsername.setBackground(new java.awt.Color(237, 239, 240));
        jTextFieldTCUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTCUsername.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTCUsername.setToolTipText("Escolha um nome de usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        jTextFieldTCEmail.setBackground(new java.awt.Color(237, 239, 240));
        jTextFieldTCEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTCEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTCEmail.setToolTipText("Insira uma conta de email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirmar Senha");

        jPasswordFieldTCConfirmarSenha.setBackground(new java.awt.Color(237, 239, 240));
        jPasswordFieldTCConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldTCConfirmarSenha.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldTCConfirmarSenha.setToolTipText("Confirme sua senha");

        rSButtonTCCriarConta.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonTCCriarConta.setText("Criar Nova Conta");
        rSButtonTCCriarConta.setToolTipText("Clique para criar sua nova conta");
        rSButtonTCCriarConta.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonTCCriarConta.setColorNormal(new java.awt.Color(255, 153, 0));
        rSButtonTCCriarConta.setColorPressed(new java.awt.Color(255, 204, 102));
        rSButtonTCCriarConta.setColorTextPressed(new java.awt.Color(4, 69, 129));
        rSButtonTCCriarConta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonTCCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonTCCriarContaActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ao criar uma conta você concorda com nossos");

        jLabelTCTermos.setForeground(new java.awt.Color(255, 153, 0));
        jLabelTCTermos.setText("Termos de serviços");
        jLabelTCTermos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPasswordFieldTCSenha.setBackground(new java.awt.Color(237, 239, 240));
        jPasswordFieldTCSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldTCSenha.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldTCSenha.setToolTipText("Insira sua senha");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelFacaLoginAqui))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelTCTermos))
                        .addComponent(jPasswordFieldTCConfirmarSenha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldTCEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldTCUsername, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonTCCriarConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldTCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFacaLoginAqui))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTCUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldTCEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldTCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldTCConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(rSButtonTCCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTCTermos))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCadastroTela.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFacaLoginAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFacaLoginAquiMouseClicked
        new MudaTela(jPanelCadastroTela, new br.com.invistafacil.telas.LoginTela());
    }//GEN-LAST:event_jLabelFacaLoginAquiMouseClicked

    private void rSButtonTCCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonTCCriarContaActionPerformed
        // Instruções do botão criar conta, e salvar o novo usuario no banco de dados.
        
        //Habilitando String no campo JPasswordfield
        String pass = new String(jPasswordFieldTCSenha.getPassword());
        String passConfirm = new String(jPasswordFieldTCConfirmarSenha.getPassword());
        
        usr.setUsername(jTextFieldTCUsername.getText());
        usr.setEmail(jTextFieldTCEmail.getText());       
        usr.setSenha(pass);
        usr.setSenha(passConfirm);               
        usr.setCpf(1);
        usr.setRg(1);
        usr.setNome("update");
        usr.setSobrenome("update");
        
        //Condições para os campos do formulário.
        if(!pass.equals(passConfirm)){                      
            JOptionPane.showMessageDialog(null, "Confirme o password Corretamente");                                
        }else if(jTextFieldTCUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo Username");
            jTextFieldTCUsername.requestFocus();          
        }else if(jTextFieldTCEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo Email");
            jTextFieldTCEmail.requestFocus();
        }else if(pass.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo senha");
           jPasswordFieldTCSenha.requestFocus();            
        }else{         
           cadastro.salvarUsuario(usr);
           new MudaTela(jPanelCadastroTela, new br.com.invistafacil.telas.LoginTela());
        }     
    }//GEN-LAST:event_rSButtonTCCriarContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFacaLoginAqui;
    private javax.swing.JLabel jLabelTCTermos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastroTela;
    private javax.swing.JPasswordField jPasswordFieldTCConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldTCSenha;
    private javax.swing.JTextField jTextFieldTCEmail;
    private javax.swing.JTextField jTextFieldTCUsername;
    private keeptoo.KGradientPanel kGradientPanel1;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonTCCriarConta;
    // End of variables declaration//GEN-END:variables
}
