/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.invistafacil.telas;

import br.com.invistafacil.business.DespesasBusiness;
import br.com.invistafacil.business.ReceitasBusiness;
import br.com.invistafacil.business.interfaces.DespesasInterface;
import br.com.invistafacil.business.interfaces.ReceitasInterface;
import br.com.invistafacil.dominio.Despesas;
import br.com.invistafacil.dominio.Receitas;
import br.com.invistafacil.repositorio.UsuarioLogado;
import javax.swing.JOptionPane;

/**
 *
 * @author George Alan
 */
public class LancamentosTela extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public LancamentosTela() {
        initComponents();
    }

    public void mostraDados() {
        UsuarioLogado.getInstance().getID();
        UsuarioLogado.getInstance().getNome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLancamentosTela = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldLTDescricaoR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rSButtonLTSalvarReceita = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jTextFieldLTTipoR = new javax.swing.JTextField();
        jTextFieldLTDataR = new javax.swing.JTextField();
        jTextFieldLTFormaRecebR = new javax.swing.JTextField();
        jTextFieldLTValorR = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLTDescricaoD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSButtonLTSalvarDespesa = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jTextFieldLTTipoD = new javax.swing.JTextField();
        jTextFieldLTFormaPagD = new javax.swing.JTextField();
        jTextFieldLTDataD = new javax.swing.JTextField();
        jTextFieldLTValorD = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1165, 762));

        jPanelLancamentosTela.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLancamentosTela.setPreferredSize(new java.awt.Dimension(1165, 762));
        jPanelLancamentosTela.setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1165, 762));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(470, 440));

        jPanel5.setBackground(new java.awt.Color(37, 168, 81));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Incluir Receita / Ganhos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Descrição");

        jTextFieldLTDescricaoR.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTDescricaoR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTDescricaoR.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTDescricaoR.setToolTipText("Descreva o que você ganhou.");
        jTextFieldLTDescricaoR.setPreferredSize(new java.awt.Dimension(400, 33));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Valor");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Forma Recebimento");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Tipo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Data");

        rSButtonLTSalvarReceita.setText("Salvar Receita");
        rSButtonLTSalvarReceita.setToolTipText("Clique para salvar a receita no sistema.");
        rSButtonLTSalvarReceita.setColorHover(new java.awt.Color(31, 143, 69));
        rSButtonLTSalvarReceita.setColorNormal(new java.awt.Color(37, 168, 81));
        rSButtonLTSalvarReceita.setColorPressed(new java.awt.Color(26, 123, 59));
        rSButtonLTSalvarReceita.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonLTSalvarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonLTSalvarReceitaActionPerformed(evt);
            }
        });

        jTextFieldLTTipoR.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTTipoR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTTipoR.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTTipoR.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTDataR.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTDataR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTDataR.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTDataR.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTFormaRecebR.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTFormaRecebR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTFormaRecebR.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTFormaRecebR.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTValorR.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTValorR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTValorR.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTValorR.setPreferredSize(new java.awt.Dimension(183, 33));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(rSButtonLTSalvarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldLTValorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLTDataR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLTFormaRecebR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldLTDescricaoR, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLTTipoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLTDescricaoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLTValorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLTFormaRecebR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLTTipoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLTDataR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(rSButtonLTSalvarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 440));

        jPanel4.setBackground(new java.awt.Color(212, 54, 54));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Incluir Despesas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Descrição");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Valor");

        jTextFieldLTDescricaoD.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTDescricaoD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTDescricaoD.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTDescricaoD.setToolTipText("Descreva o que você gastou.");
        jTextFieldLTDescricaoD.setPreferredSize(new java.awt.Dimension(400, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Data");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Forma pagamento");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Tipo");

        rSButtonLTSalvarDespesa.setBackground(new java.awt.Color(212, 54, 54));
        rSButtonLTSalvarDespesa.setText("Salvar Despesa");
        rSButtonLTSalvarDespesa.setToolTipText("Clique para salvar a despesa no sistema.");
        rSButtonLTSalvarDespesa.setColorHover(new java.awt.Color(173, 7, 7));
        rSButtonLTSalvarDespesa.setColorNormal(new java.awt.Color(212, 54, 54));
        rSButtonLTSalvarDespesa.setColorPressed(new java.awt.Color(139, 5, 5));
        rSButtonLTSalvarDespesa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonLTSalvarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonLTSalvarDespesaActionPerformed(evt);
            }
        });

        jTextFieldLTTipoD.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTTipoD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTTipoD.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTTipoD.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTFormaPagD.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTFormaPagD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTFormaPagD.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTFormaPagD.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTDataD.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTDataD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTDataD.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTDataD.setPreferredSize(new java.awt.Dimension(183, 33));

        jTextFieldLTValorD.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldLTValorD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLTValorD.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLTValorD.setPreferredSize(new java.awt.Dimension(183, 33));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldLTTipoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldLTValorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldLTFormaPagD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldLTDataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jTextFieldLTDescricaoD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonLTSalvarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLTDescricaoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLTFormaPagD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLTDataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLTTipoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLTValorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(rSButtonLTSalvarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        kGradientPanel1.setkEndColor(new java.awt.Color(4, 69, 129));
        kGradientPanel1.setkGradientFocus(-1);
        kGradientPanel1.setkStartColor(new java.awt.Color(2, 42, 79));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_add_circle_white_48dp.png"))); // NOI18N
        jLabel1.setText("Insira os Lançamentos diários");
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(750, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Controle o dinheiro que você ganha e gasta.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Insira nos campos as suas transações financeiras, para poder visualizar os relátórios na tela relátorios.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jPanelLancamentosTela.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLancamentosTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLancamentosTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonLTSalvarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonLTSalvarReceitaActionPerformed
        // Salvar Receitas.

        try {
            Receitas adicaoReceita = new Receitas();

            adicaoReceita.setDescricao(jTextFieldLTDescricaoR.getText());
            adicaoReceita.setValor(Double.parseDouble(jTextFieldLTValorR.getText()));
            adicaoReceita.setFormaRecebimento(jTextFieldLTFormaRecebR.getText());
            adicaoReceita.setTipo(jTextFieldLTTipoR.getText());
            adicaoReceita.setDataDia(jTextFieldLTDataR.getText());

            ReceitasInterface receitasBusiness = new ReceitasBusiness();
            if (receitasBusiness.salvarReceitas(adicaoReceita) != null) {
                JOptionPane.showMessageDialog(null, "Receita adicionada com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir a receita!" + ex);
        }
    }//GEN-LAST:event_rSButtonLTSalvarReceitaActionPerformed

    private void rSButtonLTSalvarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonLTSalvarDespesaActionPerformed
        // Salvar Despesas.

        try {
            Despesas adicaoDespesa = new Despesas();

            adicaoDespesa.setDescricao(jTextFieldLTDescricaoD.getText());
            adicaoDespesa.setValor(Double.parseDouble(jTextFieldLTValorD.getText()));
            adicaoDespesa.setFormaPagamento(jTextFieldLTFormaPagD.getText());
            adicaoDespesa.setTipo(jTextFieldLTTipoD.getText());
            adicaoDespesa.setDataDia(jTextFieldLTDataD.getText());

            DespesasInterface despesasBusiness = new DespesasBusiness();

            if (despesasBusiness.salvarDespesas(adicaoDespesa) != null) {
                JOptionPane.showMessageDialog(null, "Despesa adicionada com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir a despesa!" + ex);
        }
    }//GEN-LAST:event_rSButtonLTSalvarDespesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelLancamentosTela;
    private javax.swing.JTextField jTextFieldLTDataD;
    private javax.swing.JTextField jTextFieldLTDataR;
    private javax.swing.JTextField jTextFieldLTDescricaoD;
    private javax.swing.JTextField jTextFieldLTDescricaoR;
    private javax.swing.JTextField jTextFieldLTFormaPagD;
    private javax.swing.JTextField jTextFieldLTFormaRecebR;
    private javax.swing.JTextField jTextFieldLTTipoD;
    private javax.swing.JTextField jTextFieldLTTipoR;
    private javax.swing.JTextField jTextFieldLTValorD;
    private javax.swing.JTextField jTextFieldLTValorR;
    private keeptoo.KGradientPanel kGradientPanel1;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonLTSalvarDespesa;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonLTSalvarReceita;
    // End of variables declaration//GEN-END:variables
}
