/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.invistafacil.telas;

import br.com.invistafacil.business.LoginBusiness;
import br.com.invistafacil.business.interfaces.LoginInterface;
import br.com.invistafacil.dominio.Usuario;
import br.com.invistafacil.repositorio.ConexaoDB;
import br.com.invistafacil.repositorio.Sessao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author George Alan
 */
public class LoginTela extends javax.swing.JPanel {

    LoginBusiness login = new LoginBusiness();

    /**
     * Creates new form pnlHome
     */
    public LoginTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginTela = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelFormLogin = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCriarConta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTLEnderecoEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldTLSenha = new javax.swing.JPasswordField();
        rSButtonTLFazerLogin = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabelTLRecuperaSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1165, 762));

        jPanelLoginTela.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLoginTela.setPreferredSize(new java.awt.Dimension(1165, 762));
        jPanelLoginTela.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1165, 762));

        PanelFormLogin.setkEndColor(new java.awt.Color(4, 69, 129));
        PanelFormLogin.setkGradientFocus(-1);
        PanelFormLogin.setkStartColor(new java.awt.Color(2, 42, 79));
        PanelFormLogin.setkTransparentControls(false);
        PanelFormLogin.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Faça Login no Invista Fácil");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Não tem uma conta?");

        jLabelCriarConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCriarConta.setForeground(new java.awt.Color(255, 153, 0));
        jLabelCriarConta.setText("Crie uma conta aqui.");
        jLabelCriarConta.setToolTipText("Crie uma nova conta aqui");
        jLabelCriarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCriarContaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Endereço de email (ou nome de usuario)");

        jTextFieldTLEnderecoEmail.setBackground(new java.awt.Color(237, 239, 240));
        jTextFieldTLEnderecoEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTLEnderecoEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTLEnderecoEmail.setToolTipText("Insira seu email ou seu username");
        jTextFieldTLEnderecoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");

        jPasswordFieldTLSenha.setBackground(new java.awt.Color(237, 239, 240));
        jPasswordFieldTLSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldTLSenha.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldTLSenha.setToolTipText("Insira sua senha");
        jPasswordFieldTLSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        rSButtonTLFazerLogin.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonTLFazerLogin.setText("Fazer Login");
        rSButtonTLFazerLogin.setToolTipText("Clique para fazer login");
        rSButtonTLFazerLogin.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonTLFazerLogin.setColorNormal(new java.awt.Color(255, 153, 0));
        rSButtonTLFazerLogin.setColorPressed(new java.awt.Color(255, 204, 102));
        rSButtonTLFazerLogin.setColorTextPressed(new java.awt.Color(4, 69, 129));
        rSButtonTLFazerLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonTLFazerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonTLFazerLoginActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Esqueceu sua senha?");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTLRecuperaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTLRecuperaSenha.setForeground(new java.awt.Color(255, 153, 0));
        jLabelTLRecuperaSenha.setText("Recupere aqui");
        jLabelTLRecuperaSenha.setToolTipText("Recupere sua senha aqui");
        jLabelTLRecuperaSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelFormLoginLayout = new javax.swing.GroupLayout(PanelFormLogin);
        PanelFormLogin.setLayout(PanelFormLoginLayout);
        PanelFormLoginLayout.setHorizontalGroup(
            PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLoginLayout.createSequentialGroup()
                .addGroup(PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLoginLayout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addGroup(PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTLEnderecoEmail)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordFieldTLSenha)
                            .addComponent(rSButtonTLFazerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelFormLoginLayout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTLRecuperaSenha))
                    .addGroup(PanelFormLoginLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCriarConta)))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        PanelFormLoginLayout.setVerticalGroup(
            PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLoginLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCriarConta))
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTLEnderecoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldTLSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(rSButtonTLFazerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelTLRecuperaSenha))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFormLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFormLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelLoginTela.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoginTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoginTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCriarContaMouseClicked
        new MudaTela(jPanelLoginTela, new br.com.invistafacil.telas.CadastroTela());
    }//GEN-LAST:event_jLabelCriarContaMouseClicked

    private void rSButtonTLFazerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonTLFazerLoginActionPerformed
        try {
            Usuario novoUsuario = new Usuario();
            novoUsuario.setEmail(jTextFieldTLEnderecoEmail.getText());
            novoUsuario.setSenha(jPasswordFieldTLSenha.getText());

            LoginInterface loginBusiness = new LoginBusiness();

            if (loginBusiness.validaUsuario(novoUsuario) != null) {
                JOptionPane.showMessageDialog(null, "Usuario logado com sucesso");
                new MudaTela(jPanelLoginTela, new br.com.invistafacil.telas.PerfilUserTela());
            } else {
                JOptionPane.showMessageDialog(null, "Senha ou usuario invalidos");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Senha ou usuario invalidos");
        }


    }//GEN-LAST:event_rSButtonTLFazerLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel PanelFormLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCriarConta;
    private javax.swing.JLabel jLabelTLRecuperaSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLoginTela;
    private javax.swing.JPasswordField jPasswordFieldTLSenha;
    private javax.swing.JTextField jTextFieldTLEnderecoEmail;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonTLFazerLogin;
    // End of variables declaration//GEN-END:variables
}
