/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.invistafacil.telas;

import br.com.invistafacil.business.ContaBancoBusiness;
import br.com.invistafacil.business.LoginBusiness;
import br.com.invistafacil.business.PerfilUserBusiness;
import br.com.invistafacil.business.UsuarioBusiness;
import br.com.invistafacil.business.interfaces.ContaBancoInterface;
import br.com.invistafacil.business.interfaces.LoginInterface;
import br.com.invistafacil.business.interfaces.PerfilUserInterface;
import br.com.invistafacil.dominio.ContaBanco;
import br.com.invistafacil.dominio.Usuario;
import br.com.invistafacil.repositorio.ConexaoDB;
import br.com.invistafacil.repositorio.Sessao;
import br.com.invistafacil.repositorio.UsuarioLogado;
import java.sql.Connection;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author George Alan
 */
public class PerfilUserTela extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public PerfilUserTela() {
        initComponents();
    }

    public void mostraDados() {
        UsuarioLogado.getInstance().getID();
        UsuarioLogado.getInstance().getNome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPerfilUserTela = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPUTNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPUTSobrenome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPUTEmail = new javax.swing.JTextField();
        rSButtonPUTSalvarIP = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPUTUsername = new javax.swing.JTextField();
        jTextFieldPUTSenha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldRg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPUTNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rSButtonPUTSalvarIF = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPUTSaldoInicial = new javax.swing.JTextField();
        jTextFieldPUTBanco = new javax.swing.JTextField();
        jTextFieldPUTContaTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1165, 762));

        jPanelPerfilUserTela.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerfilUserTela.setPreferredSize(new java.awt.Dimension(1165, 762));
        jPanelPerfilUserTela.setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1165, 762));

        kGradientPanel1.setkEndColor(new java.awt.Color(4, 69, 129));
        kGradientPanel1.setkGradientFocus(-1);
        kGradientPanel1.setkStartColor(new java.awt.Color(2, 42, 79));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_account_circle_white_48dp.png"))); // NOI18N
        jLabel1.setText("Edite as informações do seu perfil");
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(37, 168, 81));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informações pessoais");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nome");

        jTextFieldPUTNome.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTNome.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTNome.setToolTipText("Insira o seu primeiro nome.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Sobrenome");

        jTextFieldPUTSobrenome.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTSobrenome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTSobrenome.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTSobrenome.setToolTipText("Insira o seu sobrenome.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("CPF");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("RG");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Email");

        jTextFieldPUTEmail.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTEmail.setToolTipText("Insira seu endereço de email.");

        rSButtonPUTSalvarIP.setBackground(new java.awt.Color(37, 168, 81));
        rSButtonPUTSalvarIP.setText("Salvar");
        rSButtonPUTSalvarIP.setToolTipText("Clique para salvar os dados no sistema.");
        rSButtonPUTSalvarIP.setColorHover(new java.awt.Color(31, 143, 69));
        rSButtonPUTSalvarIP.setColorNormal(new java.awt.Color(37, 168, 81));
        rSButtonPUTSalvarIP.setColorPressed(new java.awt.Color(26, 123, 59));
        rSButtonPUTSalvarIP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonPUTSalvarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonPUTSalvarIPActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Username");

        jTextFieldPUTUsername.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTUsername.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTUsername.setToolTipText("Insira o nome de usuario do sistema.");

        jTextFieldPUTSenha.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTSenha.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTSenha.setToolTipText("Insira a sua senha.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Senha");

        jTextFieldCpf.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCpf.setForeground(new java.awt.Color(102, 102, 102));

        jTextFieldRg.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldRg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldRg.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rSButtonPUTSalvarIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldPUTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(223, 223, 223))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldRg)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 203, Short.MAX_VALUE))
                                    .addComponent(jTextFieldPUTSenha)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldPUTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldPUTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPUTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(45, 45, 45))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPUTSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextFieldPUTUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextFieldPUTNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPUTSenha)
                    .addComponent(jTextFieldPUTEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextFieldCpf)
                    .addComponent(jTextFieldRg))
                .addGap(18, 18, 18)
                .addComponent(rSButtonPUTSalvarIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 109, 203));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Informações Financeiras");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Conta Tipo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Número");

        jTextFieldPUTNumero.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTNumero.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTNumero.setToolTipText("Coloque o número da conta bancária.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Banco");

        rSButtonPUTSalvarIF.setBackground(new java.awt.Color(0, 109, 203));
        rSButtonPUTSalvarIF.setText("Salvar");
        rSButtonPUTSalvarIF.setToolTipText("Clique para salvar os dados no sistema.");
        rSButtonPUTSalvarIF.setColorHover(new java.awt.Color(0, 96, 180));
        rSButtonPUTSalvarIF.setColorNormal(new java.awt.Color(0, 109, 203));
        rSButtonPUTSalvarIF.setColorPressed(new java.awt.Color(0, 77, 144));
        rSButtonPUTSalvarIF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonPUTSalvarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonPUTSalvarIFActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Saldo inicial");

        jTextFieldPUTSaldoInicial.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTSaldoInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTSaldoInicial.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPUTSaldoInicial.setToolTipText("Insira o saldo inicial da sua conta (somente números)");

        jTextFieldPUTBanco.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTBanco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTBanco.setForeground(new java.awt.Color(102, 102, 102));

        jTextFieldPUTContaTipo.setBackground(new java.awt.Color(239, 241, 242));
        jTextFieldPUTContaTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPUTContaTipo.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rSButtonPUTSalvarIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(910, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldPUTContaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldPUTBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldPUTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldPUTSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPUTContaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPUTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPUTBanco))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPUTSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(rSButtonPUTSalvarIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Seja bem vindo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Coloque abaixo os dados do seu perfil, e obtenha uma experiência personalizada.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPerfilUserTela.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPerfilUserTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPerfilUserTela, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonPUTSalvarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonPUTSalvarIPActionPerformed
        // Salvar informações pessoais.

        try {
            Usuario usuario = new Usuario();

            usuario.setUsername(jTextFieldPUTUsername.getText());
            usuario.setEmail(jTextFieldPUTEmail.getText());
            usuario.setSenha(jTextFieldPUTSenha.getText());
            usuario.setNome(jTextFieldPUTNome.getText());
            usuario.setSobrenome(jTextFieldPUTSobrenome.getText());
            usuario.setCpf(Integer.parseInt(jTextFieldCpf.getText()));;
            usuario.setRg(Integer.parseInt(jTextFieldRg.getText()));
            usuario.setId(Integer.parseInt("usuario"));

            PerfilUserInterface perfilUserBusiness = new PerfilUserBusiness();

            if (perfilUserBusiness.updateUsuario(usuario) != null) {
                JOptionPane.showMessageDialog(null, "Dados Alterados com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar fazer update dos dados");
        }
    }//GEN-LAST:event_rSButtonPUTSalvarIPActionPerformed

    private void rSButtonPUTSalvarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonPUTSalvarIFActionPerformed
        // Salvar informações financeiras da ContaBancária.

        try {
            ContaBanco contaBancaria = new ContaBanco();
            contaBancaria.getContaTipo(jTextFieldPUTContaTipo.getText());
            contaBancaria.getBanco(jTextFieldPUTBanco.getText());
            contaBancaria.getNumeroConta(Integer.parseInt(jTextFieldPUTNumero.getText()));
            contaBancaria.getSaldo(Double.parseDouble(jTextFieldPUTSaldoInicial.getText()));

            ContaBancoInterface contaBancoBusiness = new ContaBancoBusiness();

            if (contaBancoBusiness.salvarContaBanco(contaBancaria) != null) {
                JOptionPane.showMessageDialog(null, "Conta bancária salva com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar fazer o cadastro!" + ex);
        }
    }//GEN-LAST:event_rSButtonPUTSalvarIFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelPerfilUserTela;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldPUTBanco;
    private javax.swing.JTextField jTextFieldPUTContaTipo;
    private javax.swing.JTextField jTextFieldPUTEmail;
    private javax.swing.JTextField jTextFieldPUTNome;
    private javax.swing.JTextField jTextFieldPUTNumero;
    private javax.swing.JTextField jTextFieldPUTSaldoInicial;
    private javax.swing.JTextField jTextFieldPUTSenha;
    private javax.swing.JTextField jTextFieldPUTSobrenome;
    private javax.swing.JTextField jTextFieldPUTUsername;
    private javax.swing.JTextField jTextFieldRg;
    private keeptoo.KGradientPanel kGradientPanel1;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonPUTSalvarIF;
    private br.com.invistafacil.rsbuttom.RSButtonMetro rSButtonPUTSalvarIP;
    // End of variables declaration//GEN-END:variables
}
