/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.invistafacil.principal;

import br.com.invistafacil.dominio.Usuario;
import br.com.invistafacil.telas.*;
import br.com.invistafacil.repositorio.ConexaoDB;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import br.com.invistafacil.repositorio.Sessao;
import br.com.invistafacil.telas.MudaTela;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;

/**
 *
 * @author George Alan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */

    //ConexaoDB conectaBd = ConexaoDB.getInstancy(); //Instância da classe ConexãoDB.
    Usuario usr = new Usuario();

    public Principal() {
        initComponents();
       // Connection con = conectaBd.getConexao(); //Criando a conexão do banco de dados.      
        this.setExtendedState(NORMAL);
        this.setLocationRelativeTo(this);
        this.btnMHome.setSelected(true);

        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.LoginTela());

        /**
         * O código abaixo é para trocar o icone da janela do Jframe do Java,
         * usa-se uma imagen de 16x16.
         */
        URL caminhoIcone = getClass().getResource("/br/com/invistafacil/icones/Simbolo_Invistafacil_16dp.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMHome = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMVisaoGeral = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMPerfilUser = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMCadastro = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMLancamentos = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMRelatorios = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMCursoBitcoin = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        btnMCursoEdFi = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        btnSairConta = new br.com.invistafacil.rsbuttom.RSButtonMetro();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 900));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMHome.setBackground(new java.awt.Color(51, 51, 51));
        btnMHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_home_white_24dp.png"))); // NOI18N
        btnMHome.setText("Home");
        btnMHome.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMHome.setColorHover(new java.awt.Color(102, 102, 102));
        btnMHome.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMHome.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMHome.setIconTextGap(16);
        btnMHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMHomeMousePressed(evt);
            }
        });
        btnMHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMHomeActionPerformed(evt);
            }
        });

        btnMVisaoGeral.setBackground(new java.awt.Color(51, 51, 51));
        btnMVisaoGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_visibility_white_24dp.png"))); // NOI18N
        btnMVisaoGeral.setText("Visão Geral");
        btnMVisaoGeral.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMVisaoGeral.setColorHover(new java.awt.Color(102, 102, 102));
        btnMVisaoGeral.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMVisaoGeral.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMVisaoGeral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMVisaoGeral.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMVisaoGeral.setIconTextGap(16);
        btnMVisaoGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMVisaoGeralMousePressed(evt);
            }
        });
        btnMVisaoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMVisaoGeralActionPerformed(evt);
            }
        });

        btnMPerfilUser.setBackground(new java.awt.Color(51, 51, 51));
        btnMPerfilUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_account_circle_white_24dp.png"))); // NOI18N
        btnMPerfilUser.setText("User Settings");
        btnMPerfilUser.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMPerfilUser.setColorHover(new java.awt.Color(102, 102, 102));
        btnMPerfilUser.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMPerfilUser.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMPerfilUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMPerfilUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMPerfilUser.setIconTextGap(16);
        btnMPerfilUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMPerfilUserMousePressed(evt);
            }
        });
        btnMPerfilUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPerfilUserActionPerformed(evt);
            }
        });

        btnMCadastro.setBackground(new java.awt.Color(51, 51, 51));
        btnMCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_lock_white_24dp.png"))); // NOI18N
        btnMCadastro.setText("Cadastro");
        btnMCadastro.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMCadastro.setColorHover(new java.awt.Color(102, 102, 102));
        btnMCadastro.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMCadastro.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMCadastro.setIconTextGap(16);
        btnMCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMCadastroMousePressed(evt);
            }
        });
        btnMCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCadastroActionPerformed(evt);
            }
        });

        btnMLancamentos.setBackground(new java.awt.Color(51, 51, 51));
        btnMLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_add_circle_white_24dp.png"))); // NOI18N
        btnMLancamentos.setText("Lançamentos");
        btnMLancamentos.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMLancamentos.setColorHover(new java.awt.Color(102, 102, 102));
        btnMLancamentos.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMLancamentos.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMLancamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMLancamentos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMLancamentos.setIconTextGap(16);
        btnMLancamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMLancamentosMousePressed(evt);
            }
        });
        btnMLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLancamentosActionPerformed(evt);
            }
        });

        btnMRelatorios.setBackground(new java.awt.Color(51, 51, 51));
        btnMRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/finance_24dp.png"))); // NOI18N
        btnMRelatorios.setText("Relatorios");
        btnMRelatorios.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMRelatorios.setColorHover(new java.awt.Color(102, 102, 102));
        btnMRelatorios.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMRelatorios.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMRelatorios.setIconTextGap(16);
        btnMRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMRelatoriosMousePressed(evt);
            }
        });
        btnMRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRelatoriosActionPerformed(evt);
            }
        });

        btnMCursoBitcoin.setBackground(new java.awt.Color(51, 51, 51));
        btnMCursoBitcoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_bitcoin_24dp.png"))); // NOI18N
        btnMCursoBitcoin.setText("Curso Bitcoin");
        btnMCursoBitcoin.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMCursoBitcoin.setColorHover(new java.awt.Color(102, 102, 102));
        btnMCursoBitcoin.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMCursoBitcoin.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMCursoBitcoin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMCursoBitcoin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMCursoBitcoin.setIconTextGap(16);
        btnMCursoBitcoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMCursoBitcoinMousePressed(evt);
            }
        });
        btnMCursoBitcoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCursoBitcoinActionPerformed(evt);
            }
        });

        btnMCursoEdFi.setBackground(new java.awt.Color(51, 51, 51));
        btnMCursoEdFi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_school_white_24dp.png"))); // NOI18N
        btnMCursoEdFi.setText("Curso Educação Financeira");
        btnMCursoEdFi.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btnMCursoEdFi.setColorHover(new java.awt.Color(102, 102, 102));
        btnMCursoEdFi.setColorNormal(new java.awt.Color(51, 51, 51));
        btnMCursoEdFi.setColorPressed(new java.awt.Color(255, 153, 0));
        btnMCursoEdFi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMCursoEdFi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMCursoEdFi.setIconTextGap(16);
        btnMCursoEdFi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMCursoEdFiMousePressed(evt);
            }
        });
        btnMCursoEdFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCursoEdFiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMVisaoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMLancamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMCursoBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMCursoEdFi, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMVisaoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMLancamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnMRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnMCursoBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnMCursoEdFi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(3, 67, 125));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 49));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/Logo Completo Invista Fácil_24dp.png"))); // NOI18N

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_account_circle_white_24dp.png"))); // NOI18N

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setText("USER NAME");

        btnSairConta.setBackground(new java.awt.Color(3, 67, 125));
        btnSairConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/invistafacil/icones/ic_reply_white_24dp.png"))); // NOI18N
        btnSairConta.setText("SAIR");
        btnSairConta.setColorHover(new java.awt.Color(3, 67, 125));
        btnSairConta.setColorNormal(new java.awt.Color(3, 67, 125));
        btnSairConta.setColorPressed(new java.awt.Color(3, 67, 125));
        btnSairConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1080, Short.MAX_VALUE)
                .addComponent(jLabelUserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnSairConta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNomeUsuario)
                        .addComponent(btnSairConta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelUserIcon)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Códigos responsáveis pela mudança de cor dos botões do menu lateral.
    private void btnMHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMHomeActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.HomeTela());
        if (this.btnMHome.isSelected()) {
            this.btnMHome.setColorNormal(new Color(255, 153, 0));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMHomeActionPerformed

    private void btnMHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMHomeMousePressed
        this.btnMHome.setSelected(true);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMHomeMousePressed

    private void btnMPerfilUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPerfilUserActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.PerfilUserTela());
        if (this.btnMPerfilUser.isSelected()) {
            this.btnMPerfilUser.setColorNormal(new Color(255, 153, 0));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMPerfilUserActionPerformed

    private void btnMPerfilUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMPerfilUserMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(true);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMPerfilUserMousePressed

    private void btnMVisaoGeralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMVisaoGeralMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(true);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMVisaoGeralMousePressed

    private void btnMVisaoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMVisaoGeralActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.DashboardTela());
        if (this.btnMVisaoGeral.isSelected()) {
            this.btnMVisaoGeral.setColorNormal(new Color(255, 153, 0));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMVisaoGeralActionPerformed

    private void btnMLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLancamentosActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.LancamentosTela());
        if (this.btnMLancamentos.isSelected()) {
            this.btnMLancamentos.setColorNormal(new Color(255, 153, 0));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMLancamentosActionPerformed

    private void btnMLancamentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLancamentosMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(true);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMLancamentosMousePressed

    private void btnMCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCadastroMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(true);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMCadastroMousePressed

    private void btnMCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCadastroActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.CadastroTela());
        if (this.btnMCadastro.isSelected()) {
            this.btnMCadastro.setColorNormal(new Color(255, 153, 0));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMCadastroActionPerformed

    private void btnMRelatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMRelatoriosMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(true);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMRelatoriosMousePressed

    private void btnMRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRelatoriosActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.RelatoriosTela());
        if (this.btnMRelatorios.isSelected()) {
            this.btnMRelatorios.setColorNormal(new Color(255, 153, 0));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMRelatoriosActionPerformed

    private void btnMCursoBitcoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCursoBitcoinMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(true);
        this.btnMCursoEdFi.setSelected(false);
    }//GEN-LAST:event_btnMCursoBitcoinMousePressed

    private void btnMCursoBitcoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCursoBitcoinActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.BitcoinTela());
        if (this.btnMCursoBitcoin.isSelected()) {
            this.btnMCursoBitcoin.setColorNormal(new Color(255, 153, 0));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMCursoBitcoinActionPerformed

    private void btnMCursoEdFiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCursoEdFiMousePressed
        this.btnMHome.setSelected(false);
        this.btnMVisaoGeral.setSelected(false);
        this.btnMPerfilUser.setSelected(false);
        this.btnMCadastro.setSelected(false);
        this.btnMLancamentos.setSelected(false);
        this.btnMRelatorios.setSelected(false);
        this.btnMCursoBitcoin.setSelected(false);
        this.btnMCursoEdFi.setSelected(true);
    }//GEN-LAST:event_btnMCursoEdFiMousePressed

    private void btnMCursoEdFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCursoEdFiActionPerformed
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.CursoTela());
        if (this.btnMCursoEdFi.isSelected()) {
            this.btnMCursoEdFi.setColorNormal(new Color(255, 153, 0));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));

            this.btnMCursoBitcoin.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoBitcoin.setColorHover(new Color(102, 102, 102));
            this.btnMCursoBitcoin.setColorPressed(new Color(255, 153, 0));

            this.btnMRelatorios.setColorNormal(new Color(51, 51, 51));
            this.btnMRelatorios.setColorHover(new Color(102, 102, 102));
            this.btnMRelatorios.setColorPressed(new Color(255, 153, 0));

            this.btnMCadastro.setColorNormal(new Color(51, 51, 51));
            this.btnMCadastro.setColorHover(new Color(102, 102, 102));
            this.btnMCadastro.setColorPressed(new Color(255, 153, 0));

            this.btnMHome.setColorNormal(new Color(51, 51, 51));
            this.btnMHome.setColorHover(new Color(102, 102, 102));
            this.btnMHome.setColorPressed(new Color(255, 153, 0));

            this.btnMVisaoGeral.setColorNormal(new Color(51, 51, 51));
            this.btnMVisaoGeral.setColorHover(new Color(102, 102, 102));
            this.btnMVisaoGeral.setColorPressed(new Color(255, 153, 0));

            this.btnMPerfilUser.setColorNormal(new Color(51, 51, 51));
            this.btnMPerfilUser.setColorHover(new Color(102, 102, 102));
            this.btnMPerfilUser.setColorPressed(new Color(255, 153, 0));

            this.btnMLancamentos.setColorNormal(new Color(51, 51, 51));
            this.btnMLancamentos.setColorHover(new Color(102, 102, 102));
            this.btnMLancamentos.setColorPressed(new Color(255, 153, 0));
        } else {
            this.btnMCursoEdFi.setColorNormal(new Color(51, 51, 51));
            this.btnMCursoEdFi.setColorHover(new Color(102, 102, 102));
            this.btnMCursoEdFi.setColorPressed(new Color(255, 153, 0));
        }
    }//GEN-LAST:event_btnMCursoEdFiActionPerformed

    private void btnSairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairContaActionPerformed
        //conectaBd.desconecta(); //Desconecta com o banco de dados.
        new MudaTela(pnlPrincipal, new br.com.invistafacil.telas.LoginTela());
    }//GEN-LAST:event_btnSairContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMCadastro;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMCursoBitcoin;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMCursoEdFi;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMHome;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMLancamentos;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMPerfilUser;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMRelatorios;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnMVisaoGeral;
    private br.com.invistafacil.rsbuttom.RSButtonMetro btnSairConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
